Update grafana-operator dependency
aerogear/unifiedpush-operator pull request #109
Opened 2021-08-23 16:33 UTC by matskiv

## Motivation
JIRA: https://issues.redhat.com/browse/INTLY-10785

## What
Grafana-operator dependency was updated in order to pickup newer struct definitions for the CRs provided by it.

## Why
In order to avoid Unmarshalling errors.

## How
Basically `dep ensure -update github.com/integr8ly/grafana-operator`
and minor code changes to remove extra field.

## Verification Steps
Have the previous version of the operator running.
Verify that an error like this is not present in operator logs:
```
E0819 20:43:53.556597   1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha1.GrafanaDashboard: v1alpha1.GrafanaDashboardList.Items: []v1alpha1.GrafanaDashboard: v1alpha1.GrafanaDashboard.Status: v1alpha1.GrafanaDashboardStatus.Phase: readUint64: unexpected character: ÿ, error found in #10 byte of ...|,"phase":"reconcilin|..., bigger context ...|54dd6c3f2f8","id":15,"message":"success","phase":"reconciling","slug":"unifiedpush-server","uid":"Zc|...
```
Start an API proxy `oc proxy --port 1234`
Update the namespace part("redhat-rhmi-ups") in the command below and execute it:
```
curl -s localhost:1234/apis/integreatly.org/v1alpha1/namespaces/redhat-rhmi-ups/grafanadashboards/unifiedpushserver-dashboard/status -XPATCH  -H "Accept: application/json" -H "Content-Type: application/merge-patch+json" -d '{"status": {"hash": "3de09b7d992c2cdac355954dd6c3f2f8", "id": 15, "message": "success", "phase": "reconciling", "slug": "unifiedpush-server", "uid": "ZckQWaPMk"}}'
```
This will add legacy status fields to the GrafanaDashboard CR.
Now you should see error mentioned above in the operator logs.
Stop your instance of the operator.
Run the operator from this branch.
You shouldn't see the error in the logs, instead you should see a message indicating successful reconcile.

## Checklist:
- [x] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member 

## Progress
- [x] Code changes
- [ ] Version bump

2021-08-24 15:04 UTC, laurafitzgerald commented
Verified on cluster running 0.5.1 
As per the described steps, the error was present
Deployed 0.5.2-beta image which is a copy of this branch
Once that version was running the presence of the error log is gone

also noting that ```{"level":"info","ts":1629816772.985601,"logger":"unifiedpushserver-controller","msg":"PrometheusRule reconciled:","Request.Namespace":"redhat-rhmi-ups","Request.Name":"ups","PrometheusRule.Name":"unifiedpush","PrometheusRule.Namespace":"redhat-rhmi-ups","Operation":"updated"}
``` 
log was seen which had been blocked by the error fixed in this pr.

/lgtm
/approve

2021-08-24 15:06 UTC, laurafitzgerald requested changes

2021-08-24 15:06 UTC, laurafitzgerald commented on deploy/olm-catalog/unifiedpush-operator/0.5.2/unifiedpush-operator.v0.5.2.clusterserviceversion.yaml
> +  replaces: unifiedpush-operator.v0.5.1
@matskiv one final question. should we skip 0.5.1 and replace 0.5.0 cc @psturc

2021-08-24 16:20 UTC, matskiv commented on deploy/olm-catalog/unifiedpush-operator/0.5.2/unifiedpush-operator.v0.5.2.clusterserviceversion.yaml
> +  replaces: unifiedpush-operator.v0.5.1
I don't think it should be done here.
But we can do that in the CSV that we copy to integreatly-operator.

2021-08-25 08:48 UTC, laurafitzgerald approved these changes

2021-08-25 13:28 UTC, merged